services:
  saj2mqtt:
    env_file: ".env"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/home/node/saj2mqtt/src
    container_name: saj2mqtt
    expose:
      - "5000"
    ports:
      - "5000:5000"
    command: npm run start
