services:
  saj2mqtt:
    env_file: ".env"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/home/node/saj2mqtt/src
    container_name: saj2mqtt
    expose:
      - "4001"
    ports:
      - "4001:4001"
    command: npm run start
